### ISSUE TITLE
Convert Module Name to ActiveDirectoryCSDsc

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/ActiveDirectoryCSDsc#38]
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

**Comment by johlju** [comment]
@PlagueHO FYI. I seem to have a problem with CodeCov after rename (I think), see comment https://github.com/PowerShell/SqlServerDsc/issues/943#issuecomment-354131050.

**Comment by PlagueHO** [comment]
Thanks for the heads up @johlju . Thinking about it, I'm not surprised codecov isn't aware of the rename. I'll take a look at some of my other projects that have cc support and see if I can manually rename them.

**Comment by johlju** [comment]
Maybe it probably lost the connection since the project doesn’t exist anymore, and a new project must created again against the “new” repo.
