### ISSUE TITLE
xAdcsCertificateAuthority - Add Certificate Enrollment Policy Web service configuration

### ISSUE THREAD

**Issue by tehsuk** [PowerShell/ActiveDirectoryCSDsc#43]
The module is missing configuration of the Certificate Enrollment Policy Web service.

There is a cmdlet in ADCS 2012 R2 & newer to configure the web service - https://docs.microsoft.com/en-us/powershell/module/adcsdeployment/install-adcsenrollmentpolicywebservice?view=win10-ps

**Comment by PlagueHO** [comment]
I expect the MOF file for this to be something like this:
```powershell
[ClassVersion("0.1.0.0"), FriendlyName("AdcsWebEnrollment")]
class MSFT_AdcsWebEnrollment : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies the authentication type used by the Certificate Enrollment Policy Web Service. Defaults to Kerberos."), ValueMap{"Certificate","Kerberos","UserName"}, Values{"Certificate","Kerberos","UserName"}] String AuthenticationType;
    [Required, Description("Specifies the thumbprint of the certificate used by Internet Information Service (IIS) to enable support for required Secure Sockets Layer (SSL).")] String SSLCertThumbprint;
    [Write, Description("Configures the Certificate Enrollment Policy Web Service to operate in key-based renewal mode. Defaults to False.")] Boolean KeyBasedRenewal;
    [Required, Description("If the Certificate Enrollment Policy Web service is configured to use Standalone certification authority, then an account that is a member of the local Administrators on the CA is required. If the Certificate Enrollment Policy Web service is configured to use an Enterprise CA, then an account that is a member of Domain Admins is required."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Specifies whether the Certificate Enrollment Policy Web feature should be installed or uninstalled."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
```

Note: The `SSLCertThumbprint` parameter would be set to an thumbprint value. This means that the value would have to be known before compile time. This would prevent generation of the SSL cert from within the config. So a future feature might be to add the ability to search for a cert by Subject/Issuer etc.

**Comment by bgelens** [comment]
@PlagueHO It is possible to have one of each of the AuthenticationType instances on the same box, ```AuthenticationType``` would be the correct key IMO

**Comment by PlagueHO** [comment]
Good point @bgelens - so:
```powershell
[ClassVersion("0.1.0.0"), FriendlyName("AdcsCertificateEnrollmentPolicyWebService")]
class MSFT_AdcsCertificateEnrollmentPolicyWebService : OMI_BaseResource
{
    [Key, Description("Specifies the authentication type used by the Certificate Enrollment Policy Web Service.), ValueMap{"Certificate","Kerberos","UserName"}, Values{"Certificate","Kerberos","UserName"}] String AuthenticationType;
    [Required, Description("Specifies the thumbprint of the certificate used by Internet Information Service (IIS) to enable support for required Secure Sockets Layer (SSL).")] String SSLCertThumbprint;
    [Write, Description("Configures the Certificate Enrollment Policy Web Service to operate in key-based renewal mode. Defaults to False.")] Boolean KeyBasedRenewal;
    [Required, Description("If the Certificate Enrollment Policy Web service is configured to use Standalone certification authority, then an account that is a member of the local Administrators on the CA is required. If the Certificate Enrollment Policy Web service is configured to use an Enterprise CA, then an account that is a member of Domain Admins is required."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Specifies whether the Certificate Enrollment Policy Web feature should be installed or uninstalled."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
```

**Comment by PlagueHO** [comment]
@bgelens - just doing some final testing on this one and should have it through as a PR later on today.

**Comment by PlagueHO** [comment]
@bgelens - I'm ready to submit the PR for this. But I've been thinking the first version is going to need some features added later to make it more useful: instead of specifying the SSL cert thumbprint we'll want to use something that can search for a certificate that matches specific criteria such as subject and issuer and KU/EKU. This would allow a single DSC config to set everything up including requesting the certificate from a CA.

But I think I'll add this function in a later release. I can probably borrow most of the code for this from CertificateDsc/exportcertificate

**Comment by PlagueHO** [comment]
@bgelens - unfortunately I've run into a problem. The `-whatif` parameter on the `Install-AdcsEnrollmentPolicyWebService` and `Uninstall-AdcsEnrollmentPolicyWebService` doesn't actually prevent installation of the service - it actually installs/uninstalls it. This prevents us from actually testing if the service has been installed (the way we do with the other ones). There may be other ways of detecting this (perhaps checking for the IIS Webapp), but I'd be a little hesitant using this.

I've raised a uservoice for it:
https://windowsserver.uservoice.com/forums/295065-security-and-assurance/suggestions/34357522-install-adcsenrollmentpolicywebservice-ignores-wh

**Comment by bgelens** [comment]
IMO, depending on whatif throwing an error is the wrong implementation for any of these resources. It's a faulty mechanic by itself (worst kind of cmdlet design I've ever seen) and doesn't proof anything. E.g. with the CA resource, it doesn't actually proof that the CA is installed started and configured correctly, just that it tried to implement it once. Even when it failed, it would give the impression everything is alright. 

I've written this resource but unfortunnatly I am not allowed to share my code..
But to give you an idea of how I did it see this a little fragment of set.

```powershell
$cepApp = Get-WebApplication | Where-Object -FilterScript {
    $_.Applicationpool -eq 'WSEnrollmentPolicyServer' -and
    ($_.PhysicalPath -split '_')[-1] -like "$AuthenticationType*"
}

if ($null -eq $cepApp) {
    $null = Install-AdcsEnrollmentPolicyWebService @adcspwsParameters -Force -ErrorVariable errInstall
    if ($errInstall) {
        New-InvalidOperationException -Message ( @(
                "$($MyInvocation.MyCommand): "
                $($errInstall.Exception.Message)
            ) -join '' )
    }

    $cepApp = Get-WebApplication | Where-Object -FilterScript {
        $_.Applicationpool -eq 'WSEnrollmentPolicyServer' -and
        ($_.PhysicalPath -split '_')[-1] -like "$AuthenticationType*"
    }
}

$webConfigStore = [Web.Configuration.WebConfigurationManager]::OpenWebConfiguration($cepApp.path)

if ($PSBoundParameters.ContainsKey('FriendlyName')) {
    if ($webConfigStore.AppSettings.Settings['FriendlyName'].Value -ne $FriendlyName) {
        Write-Verbose -Message ( @(
                "$($MyInvocation.MyCommand): "
                $($LocalizedData.CorrectingDesiredStateMessage -f 'FriendlyName', $FriendlyName)
            ) -join '' )

        $webConfigStore.AppSettings.Settings['FriendlyName'].Value = $FriendlyName
    }
}

$webConfigStore.Save([System.Configuration.ConfigurationSaveMode]::Modified)

$appPool = Get-ChildItem -Path IIS:\AppPools | Where-Object -FilterScript { $_.Name -eq $cepApp.applicationPool }

$appPool.processModel.identityType = 'SpecificUser'
$appPool.processModel.userName = $AppPoolIdentityCredential.UserName
$appPool.processModel.password = $AppPoolIdentityCredential.GetNetworkCredential().Password
$appPool | Set-Item
```

I think you can see from this fragment how I dealt with Test and Get 😉 and that I did not rely on WhatIf at all. HTH, if you need more info, you know how te reach me

**Comment by PlagueHO** [comment]
That is great info there @bgelens - I'll see if I can incorporate it in as a function `Test-AdcsEnrollmentPolicyWebServiceState` (make it easier for me to create unit tests). I do agree that the WhatIf method of detecting this isn't ideal - it would have been much better if MSFT had implemented a test function for us as everything else relies on us being able to assume behaviors about an internal implementation (which of course could be changed). Still, I think your approach is the right one here.

I'll need to make some minor changes to support the KeyBasedRenewal options as there is 5 possible web apps that can be created (Kerberos with KeyBasedRenewal is not supported):

![image](https://user-images.githubusercontent.com/7589164/40579778-cb9e0c60-6183-11e8-9dd2-cdd04d0e3f6d.png)

Am I right in assuming this will have a dependency on the WebAdministration module?

I'll try and get this new version completed today and through.

**Comment by bgelens** [comment]
Yes, it does have the dependency with my code. Also on System.Web being loaded to make use of the WebConfigurationManager.

Funny that you ended up with 2 additional applications based on keybased renewal. I assumed it would still be 3 in total, just having the option switched on in the web.config. Now I have to rethink my resource a bit ;)
