### ISSUE TITLE
NewResourceName: AdcsOcspExtension

### ISSUE THREAD

**Issue by mavratar** [PowerShell/ActiveDirectoryCSDsc#70]
### Description

My team has been working on adding a new DSC resource module to the ActiveDirectoryCSDsc module.  This new resource module allows us to add/remove OCSP URI extensions on a Certificate Authority and to restart the CertSvc service if required.

### Proposed properties

    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("Specifies the address of the Ocsp responder from where revocation of this certificate can be checked.")] String OcspUriPath[];
    [Write, Description("Specifies if the Ocsp responder Uri should be present or absent."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Write, Description("Specifies if the service should be restarted.")] Boolean RestartService;

        AdcsOcspExtension AddOcspUriPath
        {
            OcspUriPath      = @(
                'http://primary-ocsp-responder/ocsp'
                'http://secondary-ocsp-responder/ocsp'
                'http://tertiary-ocsp-responder/ocsp'
            )
            Ensure           = 'Present'
            IsSingleInstance = 'Yes'
            Restartservice   = $true
        }

### Special considerations or limitations

N/A

**Comment by PlagueHO** [comment]
Nice @mavratar - that sounds like it would be a great edition if you're wanting to contribute? I've had the same need myself (and ended up using a script resource).

**Comment by PlagueHO** [comment]
Just an FYI, I'm changing the structure of this module shortly (today/tomorrow) to make it use the auto-documentation model (see NetworkingDsc, StorageDsc etc). See https://github.com/PowerShell/ActiveDirectoryCSDsc/issues/53. So you might want to take that into account when putting a resource together for this module.

**Comment by PlagueHO** [comment]
Actually, I see you've already submitted the PR. So ignore my comment above. I'll move this project over after your PR is merged so you don't have to do anything.

**Comment by PlagueHO** [comment]
This has been added! Thanks @mavratar 

FYI, I'm going to begin work on refactoring this module to be auto-documentation - see #53 . Just be aware that this tweaks the layout of the module just slightly. So if you're adding future stuff, just be aware of the slight changes. It's fairly obvious though and makes keeping the docs up-to-date much easier.
