### ISSUE TITLE
NewResourceName: AdcsTemplate

### ISSUE THREAD

**Issue by X-Guardian** [PowerShell/ActiveDirectoryCSDsc#86]
### Description

This resource would allow CA Templates to be added or removed on an Enterprise CA. Useful for removing legacy Templates such as `DomainController` and `DomainControllerAuthentication` etc.

#### Example usage:

```
AdcsTemplate KerberosAuthentication
{
    Name   = "DomainController"
    Ensure = 'Absent'
}
```

### Proposed properties

```
[Key, Description("Specifies the name of the CA template")] String Name;
[Write, Description("Specifies whether the CA Template should be added or removed."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
```

### Special considerations or limitations

None

**Comment by PlagueHO** [comment]
Closing this one now because it is completed.
