### ISSUE TITLE
Multiple Resources: Switch conditions missing 'break' statement

### ISSUE THREAD

**Issue by devopsjesus** [PowerShell/ActiveDirectoryCSDsc#87]
#### Details of the scenario you tried and the problem that is occurring
Several resources are using switch conditions that are missing the break statement within the scriptblock, causing the switch to evaluate all the conditions.

#### Verbose logs showing the problem
n/a

#### Suggested solution to the issue
Ideally, the switch statements should be replaced with if statements (more efficient, less complexity), but at a minimum, the break statement should be added to each switch conditional across resources.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
n/a
```

#### The operating system the target node is running
n/a

#### Version and build of PowerShell the target node is running
n/a

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by PlagueHO** [comment]
Good catch @devopsjesus - thanks for raising this issue. Better unit tests should also be used to effectively catch this.

You're right - this should be if...else blocks. Happy to take a PR or wait to get a fix in (I'm a bit snowed under at the moment). It would be important to include tests that actually checked this (which is pretty easy).

**Comment by PlagueHO** [comment]
I'll pick this one up because I need to write some code or I'll go nuts! :grin:
